#!/bin/bash
#
# MPick System GNU.
# Programmer: Martin Richard Sanders.
# E-mail    : mpick.system@gmail.com
#
# Commands:
#
# 	WHO
#	LISTU
#	LIST-FILES
#

echo ""
echo "MPick System"
echo -n "Username: "
read  username
stty -echo
echo -n "Password: "
read  password
stty echo
login_result=`grep $username DATABASE/SYSTEM | awk -F: '{print $2}'`

mpick_main_function ()
{
while true 
do
	echo -n ">"
	read mpick_command
	if [ "$mpick_command" == "LOGOFF" ] ; then
		sed -i "s/0001:$username/0001:/g" DATABASE/ACC
		echo ""
		echo "Exiting MPick"
		echo ""
		exit 1
	elif [ "$mpick_command" == "LISTU" ] ; then
		echo ""
		echo "Line USER"
		awk -F: '{print $1, $2}' DATABASE/ACC
		echo ""
		mpick_main_function
	elif [ "$mpick_command" == "LIST-FILES" ] ; then
		echo ""
		echo "Filename"
		awk -F: '{print $1}' DATABASE/MD 
		echo ""
		mpick_main_function
	elif [ "$mpick_command" == "WHO" ] ; then
		grep "$username" DATABASE/ACC | awk -F: '{print $1, $2}'
		echo ""
	else
		echo ""
		mpick_main_function
	fi
done
}


if [ "$login_result" == "$password" ] ; then
	sed -i "s/0001:/0001:$username/g" DATABASE/ACC
	echo ""
	echo ""
        echo "MPick System Release 0.5"
	echo ""
        echo "LOGGOFF     to logoff MPick System"
        echo "LIST-FILES  to list available files"
	echo "LISTU       to show users logged in"
        echo "WHO         to show username"
        echo ""
	mpick_main_function
else
	echo "Login failed."
fi

