#!/usr/bin/python3
#
# Mpick System.
# Programmer: Martin Sanders
# E-Mail    : mpick.system@gmail.com

def tcl ():
	tcl_command = ''
	while tcl_command != "OFF":
		tcl_command = input('>');
		if tcl_command == 'LISTU':
			print('WHO command');

	# Message, and exit.
	print('\nExiting MPick\n')
	quit()

# Built in commands.
def built_in_commands():
	print("\nCOMMANDS AVAILABLE:")
	print("OFF")
	print("WHO")
	print("LISTU")
	print("LIST-FILES\n")
	return

# Function to authentica login.
def authenticate(username,password):
	login_file = "DATABASE/LOGINS";
	read_login_file = open(login_file, "r")
	for login_lines in read_login_file:
		login_line = login_lines.split(':')
		username_stored = login_line[1]
		password_stored = login_line[2]
		password_stored = password_stored.rsplit()
		username_stored = username_stored.rsplit()
		if username_stored == username:
			if password_stored == password:
				built_in_commands()
				tcl()
				return




# Start of program.
system_file = "DATABASE/SYSTEM"
read_system_file = open(system_file, "r")
for release_system_file_lines in read_system_file:
	release_line = release_system_file_lines.split(':')
	release_type = release_line[0]
	release_number = release_line[1]
	release_number = release_number[:-1]
	if release_type == 'Release':
		release_version = str(release_number)

print('\nRelease ' + release_version)
username = input('Username: ')
password = input('Password: ')
username = username.rsplit()
password = password.rsplit()
authenticate(username,password)
